name: Deploy to Alibaba Cloud ECS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.0'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: npm run build

      - name: Archive static files
        run: tar -czf out.tar.gz -C out .

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ECS_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.ECS_SERVER }} >> ~/.ssh/known_hosts

      - name: Copy to ECS
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no out.tar.gz ${{ secrets.ECS_USER }}@${{ secrets.ECS_SERVER }}:/tmp/
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.ECS_USER }}@${{ secrets.ECS_SERVER }} "sudo tar -xzf /tmp/out.tar.gz -C /usr/share/nginx/html/react/ && sudo rm /tmp/out.tar.gz"
